### ISSUE TITLE
Unable to connect to host database

### ISSUE THREAD

**Issue by jish** [kdelfour/lychee-docker#7]
I'm having trouble connecting to the database. I'm using the credentials from the Readme:

https://github.com/kdelfour/lychee-docker/blob/657db7263f188926a5aed75b76ca0a51135fb154/README.md#usage

<img width="585" alt="screen shot 2016-07-31 at 12 35 39 pm" src="https://cloud.githubusercontent.com/assets/1817/17278846/9cbd2bb6-571b-11e6-96f4-e2cf374ef16e.png">

> "Unable to connect to host database because access was denied. Double-check your host, username and password and ensure that access from your current location is permitted."

**Comment by jish** [comment]
I had to connect to the container and run `apt-get update` and `apt-get upgrade`, then `service mysql start`. That seems to resolve the problem.

**Comment by Superraiden** [comment]
Messing with the src code I managed to get a "Server sent charset unknown to the client. Please, report to the developers" from mysqli connect (Database.php Line 85).

Following this Stackoverlfow question, I set the default charset to UTF-8 and it worked
https://stackoverflow.com/questions/43437490/pdo-construct-server-sent-charset-255-unknown-to-the-client-please-rep

Also for IIS users, don't forget to give 'IUSR' access to data and upload!
